disabled_rules:
  - trailing_whitespace
  - type_body_length
  - switch_case_alignment

opt_in_rules:
  - empty_count
  - explicit_init
  - sorted_imports

line_length:
  warning: 180
  error: 200

type_name:
  min_length: 3

identifier_name:
  min_length: 2

file_length:
  warning: 400
