disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init
  - sorted_imports

line_length:
  warning: 180
  error: 200

type_name:
  min_length: 3

identifier_name:
  min_length: 2

function_body_length:
  warning: 40

file_length:
  warning: 400
